---
apps_mode: core  # core | full

apps_mail_variant: thunderbird  # thunderbird | betterbird | none

apps_enable_heavy_media: false      # obs-studio
apps_enable_creative: false         # inkscape, gimp
apps_enable_private_messaging: false # signal
apps_enable_uni_apps: false         # graphviz/gephi or keep those in devtools/uni if you prefer

apps_pacman_core:
  - firefox
  - chromium
  - libreoffice-fresh
  - vlc

apps_pacman_media_heavy:
  - obs-studio

apps_pacman_creative:
  - inkscape
  - gimp

apps_pacman_private_messaging:
  - signal-desktop

apps_pacman_uni:
  - graphviz
  - gephi

apps_aur_mail_betterbird:
  - betterbird-bin

apps_extra_pacman: []
apps_extra_aur: []
apps_extra_flatpak: []
