---
# apps_mode: core | uni | private | full
apps_mode: core

# Global default (set in group_vars/all.yml)
apps_mail_variant: thunderbird  # thunderbird | betterbird | none

apps_enable_heavy_media: false
apps_enable_creative: false
apps_enable_private_messaging: false
apps_enable_uni_apps: false

apps_pacman_core:
  - firefox
  - libreoffice-fresh
  - vlc
  # chromium optional; if you really want everywhere add here
  - chromium

apps_pacman_media_heavy:
  - obs-studio

apps_pacman_creative:
  - inkscape
  - gimp

apps_pacman_private_messaging:
  - signal-desktop

apps_pacman_uni:
  - graphviz
  - gephi

apps_aur_mail_betterbird:
  - betterbird-bin

apps_extra_pacman: []
apps_extra_aur: []
apps_extra_flatpak: []
