---
# devtools_mode: core | full | work
devtools_mode: core

# Optional feature toggles (few + sane)
devtools_enable_containers: false
devtools_enable_tex: true
devtools_enable_tex_extra: false
devtools_enable_lang: true
devtools_enable_admin: false

devtools_pacman_core:
  - python-uv
  - pandoc
  - gcc
  - gdb
  - valgrind
  - make
  - cmake
  - ninja
  - pkgconf
  - shellcheck
  - shfmt
  - hyperfine
  - just

devtools_pacman_lang:
  - go

devtools_pacman_containers:
  - docker
  - docker-compose

devtools_pacman_admin:
  - ansible

devtools_pacman_tex_base:
  - texlive-core

devtools_pacman_tex_extra:
  - texlive-latexextra
  - texlive-pictures

devtools_pacman_work:
  - terraform
  - aws-cli
  - openfortivpn

devtools_aur_core: []
devtools_extra_pacman: []
devtools_extra_aur: []
devtools_extra_flatpak: []
