---
- name: Hardware | zsa | Install packages
  ansible.builtin.include_role:
    name: packages
    tasks_from: install.yml
  vars:
    packages_pacman_packages: "{{ hardware_pacman_packages_zsa }}"
    packages_aur_packages: "{{ hardware_aur_packages_zsa }}"

- name: Hardware | zsa | Install udev rules
  become: true
  ansible.builtin.copy:
    src: "{{ hardware_zsa_udev_rules_src }}"
    dest: "{{ hardware_zsa_udev_rules_dest }}"
    owner: root
    group: root
    mode: "0644"
  notify: Reload udev rules
