desktop_enable_qtile: true
desktop_enable_kde: true

# sane defaults
devtools_mode: core
apps_mode: core

hardware_enable_zsa: true
hardware_enable_fwupd: true
hardware_enable_printer: false
hardware_enable_plover: false

storage_enable_snapper: true
storage_backup_tool: borg

# security defaults
security_add_user_to_wheel: true
security_require_wheel_for_sudo: true
security_ensure_sshd_disabled: true
security_enable_sshd: false
security_apply_sysctl_baseline: true

# docker group default off
security_enable_docker_group: false
security_add_user_to_docker: false

apps_mail_variant: thunderbird

hardware_enable_logitech: true

