devtools_mode: work
apps_mode: core

apps_enable_heavy_media: true
apps_enable_creative: false
apps_enable_private_messaging: false
apps_enable_uni_apps: false

security_enable_docker_group: true
security_add_user_to_docker: true
